import base64
import hashlib
import hmac
import json
import os
from datetime import datetime, timezone, timedelta


def create_admin_token(admin_id: int, email: str) -> str:
    secret = os.getenv("ADMIN_TOKEN_SECRET", "crowdsense-dev-secret")
    payload = {
        "sub": admin_id,
        "email": email,
        "exp": (datetime.now(timezone.utc) + timedelta(hours=8)).isoformat(),
    }
    payload_json = json.dumps(payload, separators=(",", ":")).encode()
    payload_b64 = base64.urlsafe_b64encode(payload_json).decode().rstrip("=")
    signature = hmac.new(secret.encode(), payload_b64.encode(), hashlib.sha256)
    signature_b64 = base64.urlsafe_b64encode(signature.digest()).decode().rstrip("=")
    return f"{payload_b64}.{signature_b64}"


def verify_admin_token(token: str) -> dict:
    """Verify token generated by create_admin_token.

    Returns payload dict if valid, raises HTTPException otherwise.
    """
    secret = os.getenv("ADMIN_TOKEN_SECRET", "crowdsense-dev-secret")
    try:
        payload_b64, signature_b64 = token.split('.')
        expected_sig = hmac.new(secret.encode(), payload_b64.encode(), hashlib.sha256).digest()
        expected_sig_b64 = base64.urlsafe_b64encode(expected_sig).decode().rstrip('=')
        if not hmac.compare_digest(expected_sig_b64, signature_b64):
            raise ValueError("Invalid signature")
        # Pad base64 strings for decoding
        padding = '=' * (-len(payload_b64) % 4)
        payload_json = base64.urlsafe_b64decode(payload_b64 + padding)
        payload = json.loads(payload_json)
        # Check expiration
        exp = datetime.fromisoformat(payload["exp"]).replace(tzinfo=timezone.utc)
        if datetime.now(timezone.utc) > exp:
            raise ValueError("Token expired")
        return payload
    except Exception as e:
        raise ValueError(f"Token verification failed: {e}")
